### ISSUE TITLE
Do we need RepeatMasker with RC.representative.fa after HELIANO running

### ISSUE THREAD

**Issue by baozg** [Zhenlisme/heliano#2]
Hi, @Zhenlisme 

Thanks for this nice tool! I am just curious about the postprocessing of `Heliano` output. Should we use `RC.representativate.fa` for RepeatMasker to get an estimation of the fragmented one? Or `RC.representativate.bed` should be the result I should use to complementary with other TEs annotation gff (such as EDTA, RepeatModeler2)

**Comment by Zhenlisme** [comment]
Hello Zhigui,

Thank you for utilizing our tool. HELIANO is designed to predict complete insertions of Helitron-like elements (HLE), with the limitation that fragmented insertions will not be reported. To identify fragmented insertions, we recommend running RepeatMasker or BLASTN using HELIANO predictions as the query.

It's worth noting that EDTA employs HelitronScanner as an engine, leading to a higher false positive rate (FPR). As a complementary approach, consider running RepeatModeler2, which has a lower FPR but predicts few of HLEs. Incorporate the RepeatModeler2-unique HLEs into your HLE database for a more comprehensive dataset.

Additionally, be cautious about other TEs inserting into long HLEs, potentially inflating sequence lengths. For added reliability, we suggest masking the HLE database with a trusted non-HLE TE database when incorporating it into your overall TE database.

Best regards,

**Comment by baozg** [comment]
Thanks for your prompt suggestion. I tried HELIANO with A.thaliana, and the result looks good. Now I want to replace `HelitronScanner` with `HELIANO` in EDTA to deliver better overall TE annotation for our pangenome project. RepeatModeler didn't take too much effort on LTR, which is highly abundant in plant genomes. For EDTA, integrating HELIANNO seems quite straightforward.

**Comment by Zhenlisme** [comment]
Hi,
I will download this version of maize genome and rerun your command to see what we can do to the result.
Best,
Zhen

**Comment by Zhenlisme** [comment]
> I have a follow-up question about this. I tried to run `heliano` with maize B73_v5, but even after the consensus step, the helitron candidates are still too big (605Mb vs 391Mb). Do you have any suggestions?
> 
> ```shell
> heliano -g maize.fa -is1 0 -is2 0 -n 20 -o b73_helianno -p 1e-5 -s 30
> heliano_cons -g maize.fa -r b73_helianno/RC.representative.bed -o b73_helianno_cns -n 20
> ```

Hello Zhigui,
Maybe try this command line:  `heliano -g maize.fa -is1 1 -n 20 -o b73_helianno -p 1e-5 -s 30`. Because most Helitrons inserted between A and T nucleotides, using the parameter 'is1 1' will allow HELIANO precisely look for Helitron queries whose insertion sites are 'AT'. I tried and the file size of RC.representative.fa is only 29M.

All the best,
Zhen

**Comment by baozg** [comment]
Thanks for the quick check. But how should I decide to use `-pt,-is1, -is2` properly? I follow the description in your paper `For O.sativa genome, we ran HELIANO with the parameter ‘-s 30 -is1 0 -is2 0 -n 20 -p 1e5’`.

**Comment by Zhenlisme** [comment]
Hi Zhigui,

That is a very good question. For a precise and quick search, I always use the strigent parameter '-pt 1 -is1 1 -is2 1 -p 1e-5 -s 30 -pt 1 -sim_tir 100' that considered the preferred insertion sites of HLE. For big or complex genomes (e.g., maize genome), I just recommeded you use the strigent parameters. If you want to explore more in your interested genome, you can use the loose parameter set, e.g., '-is1 0 -is2 0 -sim_tir 90', and you will have more predictions. Note that the parameters 'is2' and '-sim_tir' are only for Helentrons, and 'is1' and '-pt' are only for Helitrons. 

All the best,
Zhen

**Comment by baozg** [comment]
Thanks for your detailed explanation. Maybe this could be added to FAQ of `HELIANO` to guide the users in choosing parameters. I found lots of non-Helitron TEs in maize with `-is1 0 -is2 0 -sim_tir 90`, so even with more stringent parameter, people still filter by other TEs.

**Comment by Zhenlisme** [comment]
Hi Zhigui,
Thank you for your suggestion about FAQ.

You are right, I found some predicted Helitrons are LTRs with the loose parameters. The reason might be due to the high density of TEs in maize genome (about 85% maize genome is made up of TEs). It is expected to see nested TEs in some predicted Helitrons, which is actually a problem for almost all TE annotators. This issue might be solved in future versions of HELIANO... But currently, as I suggeted before, the solution is to mask the HLE database with a trusted non-HLE TE database when incorporating it into your overall TE database.
Best,
Zhen
