### ISSUE TITLE
About noauto helitron detection

### ISSUE THREAD

**Issue by lyysxb** [Zhenlisme/heliano#6]
Hi,

Thank you very much for your open source contribution. I would like to ask how the 'noauto' Helitron is detected in this code, and specifically, in which method is it implemented?

**Comment by Zhenlisme** [comment]
Hi,

Thank you for using HELIANO.

I am not sure if I understand correctly to your question. To detect nonautonomous Helitron insertions, HELIANO firstly identify the significantly co-occuring LTS-RTS pairs in a given genome. After obtaining the LTS-RTS pairs, HELIANO will recover the nonauto coordination based on the coord of LTS and RTS.

All the best,
Zhen

**Comment by halonlinctos** [comment]
！

**Comment by halonlinctos** [comment]
I used HELIANO to test the genomes of peanut, corn and strain Fo5176 mentioned in the example, using the parameters provided in usage 
heliano -g test.fa -is1 0 -is2 0-o test_opt -w 15000 
I have the following questions and would like to ask you:
 1. Among the three genomes, only Fo5176 contains HLE1 and HLE2 in the results, and only HLE1 is found in peanut and corn. As corn is one of the plants with the richest transposon content, why is HLE2 not detected?
 2.   I have used helitronscanner to detect several maize assembled genomes. Taking maize Mo17 as an example, 35,819 helitron transposons were detected. However, using your HELIANO, only 430 were detected in the RC.representative.bed file, and 703 were detected in peanuts. These numbers are far lower than helitronscanner. Although the false positive rate of helitronscanner is relatively high, I think this gap is unlikely to be due to this reason. Is there something wrong with my parameter settings? 
 3. After obtaining the RC.representative.bed file, is this the final transposon identified? Is there any further operation required? 
 4. Frequently asked questions，you say strigent parameter '-pt 1 -is1 1 -is2 1 -p 1e-5 -s 30 -pt 1 -sim_tir 100' ，why are there double ‘-pt’ ，is it a 'Typographical error'？or anything else
 Looking forward to your response，thanks！

**Comment by Zhenlisme** [comment]
- HLE1 and HLE2 are two divergent Helitron groups/variants. Their distribution accross the tree of life is quite mosaic and they don't have to co-occur in a given genome. Most plant genomes contain HLE1 group only, although we do find the presence of HLE2 sequences in some plant species. You can check it out in our [paper ](https://academic.oup.com/view-large/figure/482225799/gkae679fig6.jpg)(Fig. 6A). 
- Your results in maize genomes seem normal in terms of prediction number. HelitronScanner uses structural-based strategy to detect Helitron (only HLE1), which searches LTS motif (TC...) and RTS motifs (...CTRR) in a given genome with the LCV model. Although it is tested being quite sensitive for some plant species, the high prevalence of LTS/RTS motifs in genomes (you can even find them in the human genome which does not contain Helitrons) results in the high FPR of HelitronScanner. HELIANO is designed to try to avoid high false positive rate via a strict statisticaly test which filters most false positives.
- Note that HELIANO only outputs structurally-complete insertions, meaning that degenerated copies might be missed from HELIANO predictions. See [FAQ1](https://github.com/Zhenlisme/heliano?tab=readme-ov-file#1-how-to-get-fragmented-copies-of-hles).
- That is definitely a typo in FAQ2, thanks. I have corrected it.

Best,
Zhen

**Comment by halonlinctos** [comment]
Thank you very much for your reply! 
I have discussed this with my senior and teacher, and their opinions are exactly the same as your reply. Accurately identifying Helitron transposons is one of the necessary parts of my project. Your tool is very valuable to me. In order to better play its role, if it is convenient for you, can you upload the development version of HELIANO or send it to the mailbox 65520407@qq.com? We want to train the HMM model and try to find some Helitron with less degradation.
Thanks！
